# ==========================================
# Ontology Configuration File
# ==========================================
# This file contains all configurable parameters for the ontology management system
# Modify these values to adapt the system to different ontology projects

# ==========================================
# Basic Settings
# ==========================================
#ontology:
  # Base URI for the ontology namespace (must end with # or /)
base_uri: "https://raw.githubusercontent.com/cnherrera/Exa-AToW_onto/refs/heads/main/test_ontology_exaatow.ttl#"

# Default language for labels and comments
default_lang: "en"

# Directory containing JSON definition files
files_dir: "files"

# Automatically initialize ontology structure on instantiation
auto_init: false

# ==========================================
# Namespace Bindings
# ==========================================
# Define all namespaces used in the ontology
# Format: prefix: uri
namespaces:
  exa-atow: "https://raw.githubusercontent.com/cnherrera/Exa-AToW_onto/refs/heads/main/test_ontology_exaatow.ttl#"
  skos: "http://www.w3.org/2004/02/skos/core#"
  owl: "http://www.w3.org/2002/07/owl#"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  xsd: "http://www.w3.org/2001/XMLSchema#"
  eurio: "http://data.europa.eu/s66#"
  hpc_onto: "https://hpc-fair.github.io/ontology/#"
  dc: "http://purl.org/dc/elements/1.1/"
  dcterms: "http://purl.org/dc/terms/"
  foaf: "http://xmlns.com/foaf/0.1/"
  schema: "http://schema.org/"

# ==========================================
# Data Source Files
# ==========================================
# Define which JSON files to load for different ontology components
data_sources:
  # Main class definitions
  main_classes:
    file: "main_classes.json"
    parent_class: null  # null means no default parent
  
  # Subclass definitions with their default parent classes
  subclasses:
    - file: "sub_HPC_classes.json"
      parent_class: "HPCResource"
    
    - file: "sub_PIE_classes.json"
      parent_class: "ProcessorIndicatorEstimator"
    
    - file: "sub_PhysChar_classes.json"
      parent_class: "PhysicalCharacteristic"
    
    - file: "sub_Job_classes.json"
      parent_class: "Job"
    
    - file: "sub_Workflow_classes.json"
      parent_class: "Workflow"
  
  # Property definitions
  properties:
    - "properties_workflow.json"
    - "properties_HPC.json"
  
  # Restriction definitions
  restrictions:
    - "add_restrictions_hasValue_hasUnit.json"
  
  # Instance definitions
  instances:
    - "instances_workflow.json"

# ==========================================
# Global Properties
# ==========================================
# Define properties that should be added globally to the ontology
global_properties:
  - property_name: "hasValue"
    property_type: "DatatypeProperty"
    range: "XSD:decimal"
    pref_label:
      en: "has numeric value"
      fr: "a valeur numérique"
    comment:
      en: "Numeric value."
      fr: "Valeur numérique"
  
  - property_name: "hasUnit"
    property_type: "ObjectProperty"
    range: "XSD:string"
    pref_label:
      en: "has unit"
      fr: "a unité"
    comment:
      en: "Unit of measurement."
      fr: "Unité de mesure"

# ==========================================
# Output Settings
# ==========================================
output:
  # Default output file for serialization
  default_file: "exaatow_ontology.ttl"
  
  # Default serialization format (turtle, xml, n3, json-ld, etc.)
  default_format: "turtle"
  
  # Generate visualization
  visualization:
    enabled: false
    output_file: "ontology_graph.html"
    height: "800px"
    physics: true
  
  # Dump ontology back to JSON files
  dump_to_json: false

